on:
  push:
    branches: [ main ] 
  pull_request_target: 
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets Access
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "❌ Secret is NOT accessible!"
            exit 1
          else
            echo "✅ Secret is accessible!"
          fi
